### ISSUE TITLE
Add `csctl get users`

### ISSUE THREAD

**Issue by ashleyschuett** [containership/csctl#63]
### Description
In order to use csctl in `cluster-manager` we need to be able to get all users from an organization using endpoint `/organizations/{{.OrganizationID}}/users`.

This feature will need to get us the same information to have parity with https://github.com/containership/cluster-manager/blob/master/pkg/resources/users.go

#### Why should this feature be added?
This is part of the ongoing process of phasing out the `request` package in cluster-manger.

**Comment by mattkelly** [comment]
I believe I have this on a branch in my branch graveyard™; assigning to myself so we're not duplicating work.
