### ISSUE TITLE
Add `csctl get autoscaling-policy --cluster cluster-uuid`

### ISSUE THREAD

**Issue by ashleyschuett** [containership/csctl#65]
### Description
In order to use csctl in `cluster-manager` we need to be able to get all autoscaling policies for a cluster using endpoint `https://github.com/containership/cluster-manager/blob/master/pkg/resources/autoscaling_policy.go`.

This feature will need to get us the same information to have parity with https://github.com/containership/cluster-manager/blob/master/pkg/resources/autoscaling_policy.go

#### Why should this feature be added?
This is part of the ongoing process of phasing out the `request` package in cluster-manger.

**Comment by mattkelly** [comment]
This is already done:

```
➜ csctl get asp -h
Get an autoscaling policy or list of autoscaling policies

Usage:
  csctl get autoscaling-policy [flags]

Aliases:
  autoscaling-policy, asp, asps, autoscaling-policies

Flags:
      --cluster string        cluster to use
  -h, --help                  help for autoscaling-policy
      --organization string   organization to use

Global Flags:
      --config string   config file (default is ~/.containership/csctl.yaml)
  -m, --mine            only list resources your user owns
  -o, --output string   output format
```
